### ISSUE TITLE
the script freezes up without any output

### ISSUE THREAD

**Issue by kouroshparsa** [tommyau/indelseek#1]
I tried running the script as:
```
./indelseek.pl --refseq /tmp/HG19_WholeGenomeFASTA/genome.fa --samtools /usr/local/bin/samtools --max_distance 7 --skip_lowqual --skip_lowdepth --skip_lowaf --min_af 0.05 --min_depth 500 --depth_bam private.bam>out.vcf
```

I waited for over 4 hours and it did not output anything. My bam file is 70MB.

**Comment by tommyau** [comment]
Hi,
Your command will make indelseek waiting forever because it is expecting SAM alignments from STDIN pipe.
Please kindly refer to the usage and modify the command to something like:
`samtools view private.bam | ./indelseek.pl ......`

**Comment by kouroshparsa** [comment]
Thanks a lot. I tried it with the samtool output and it worked.

**Comment by kouroshparsa** [comment]
although I got this in the stderror output:
```
depth: invalid option -- 'd'
open: No such file or directory
depth: invalid option -- 'd'
open: No such file or directory
depth: invalid option -- 'd'
open: No such file or directory
```

**Comment by tommyau** [comment]
Glad that it does not freeze now.
Could you provide the full command to see if there is a typo in command line parameters or really a bug?

**Comment by kouroshparsa** [comment]
```
/usr/local/bin/samtools view private.bam|./indelseek.pl --refseq /tmp/HG19_WholeGenomeFASTA/genome.fa --samtools /usr/local/bin/samtools --max_distance 10 --min_af 0.01 --skip_lowdepth --min_depth 500 --depth_bam "private.bam">out.vcf
```

**Comment by tommyau** [comment]
The command looks fine at the moment.
Is there any space or other special characters in BAM file name?
Please try:
`/usr/local/bin/samtools view private.bam`
to confirm your samtools is working properly.

**Comment by kouroshparsa** [comment]
That command works fine and  there is no funny character in the filename.
I suspect that the problem is my version of samtools does not like the
`$samtools depth -d $max_samtools_depth -r $region -q $quality_threshold $depth_bam`

```
Version: 0.1.18 (r982:295)

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         tview       text alignment viewer
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes
```

I can see that the latest version of samtools has the `depth -d` option:
http://www.htslib.org/doc/samtools.html
but the older version does not:
http://www.htslib.org/doc/samtools-0.1.19.html

so updating samtools will likely fix it.
Thanks

**Comment by tommyau** [comment]
o yes, samtools 0.1.18 does not work. At least version 1.3 is needed as stated in README. Please try to use a newer samtools.
